### PR TITLE
Mean bias

### PR DESCRIPTION
**Pull request by henriquelettieri**
The first pull request to implement the halo bias in master

### CODE REVIEW

**Review by vitenti — CHANGES_REQUESTED** [review]
Add a minimal documentation and unit tests to halo bias objects.

**Comment by vitenti** [comment]
@henriquelettieri and @eduardojsbarroso this pull request is just waiting for you to add minimal documentation and unit tests to halo bias objects.

**Comment by eduardojsbarroso** [comment]
Ok, I just don't know if I can do it this week

**Comment by eduardojsbarroso** [comment]
> @henriquelettieri and @eduardojsbarroso this pull request is just waiting for you to add minimal documentation and unit tests to halo bias objects.

I didn't find a good reference for the bias in `nc_halo_bias_st_ellip.c` object. I can deduce the bias function from the code but I do not know what the new parameters mean to write on the documentation. Do you guys have a reference for this equation?

**Pull request merged**
